---
language: node_js
node_js:
  - "7"
env:
  global:
    - COVERAGE=false
matrix:
  include:
    - env: COVERAGE=true
after_success:
  - "[ $COVERAGE == false ] || npm run istanbul -- --report text-summary"
